version: '3'
services:
  whatsapp_bot:
    build:
      context: .
    volumes:
      - "./:/workspace"
    ports: 
      - "5000:5000"
    command: "node gateway.js identifier 5000"
    working_dir: /workspace

